### ISSUE TITLE
[Bug]: Item share - Name of item is cropped out

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I wanted to share my current weapon on twitter for the crew3 quest. When I the picture of my weapon got generated, the name was cropped out because the name is too long. Epic Superior Ice Storm Staff of Attack

![image](https://user-images.githubusercontent.com/8630518/205566245-4c7ace39-1c94-4381-b4cd-5960712884d3.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed

**Comment by SivDraconis** [comment]
@neothon - here's a case where it still doesn't fit

https://twitter.com/DraconisSiv/status/1603182536104247296
