### ISSUE TITLE
[Bug]: It is possible to keep fighting while a potion transaction is processing

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When using a potion in a fight, the **Fight**, **Backpack** and **Flee** icons will disappear for a spinning clock while waiting for the transaction to complete. 

You can keep on fighting while the transaction processes if you click on '1' or on the 'auto play' button. If you die before the healing potion transaction goes through. You will be able to get healed by the potion, but you still be dead.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed

**Comment by Brainiac1830** [comment]
> fixed

Not fixed, can still click on **auto play** to continue fighting while there's a potion transaction in process.
